create table `users` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `email_verified_at` timestamp null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `users` add unique `users_email_unique`(`email`);
create table `password_reset_tokens` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `password_reset_tokens` add primary key (`email`);
create table `failed_jobs` (`id` bigint unsigned not null auto_increment primary key, `uuid` varchar(255) not null, `connection` text not null, `queue` text not null, `payload` longtext not null, `exception` longtext not null, `failed_at` timestamp not null default CURRENT_TIMESTAMP) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `failed_jobs` add unique `failed_jobs_uuid_unique`(`uuid`);
create table `personal_access_tokens` (`id` bigint unsigned not null auto_increment primary key, `tokenable_type` varchar(255) not null, `tokenable_id` bigint unsigned not null, `name` varchar(255) not null, `token` varchar(64) not null, `abilities` text null, `last_used_at` timestamp null, `expires_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `personal_access_tokens` add index `personal_access_tokens_tokenable_type_tokenable_id_index`(`tokenable_type`, `tokenable_id`);
alter table `personal_access_tokens` add unique `personal_access_tokens_token_unique`(`token`);
alter table `users` add `type` enum('user', 'restaurant', 'courier', 'admin') not null;
create table `foods` (`id` bigint unsigned not null auto_increment primary key, `restaurantid` bigint unsigned not null, `name` varchar(255) not null, `image_url` varchar(255) not null, `description` varchar(255) not null default 'No description provided.', `price` int not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `foods` add constraint `foods_restaurantid_foreign` foreign key (`restaurantid`) references `users` (`id`) on delete cascade;
create table `orders` (`id` bigint unsigned not null auto_increment primary key, `userid` bigint unsigned not null, `status` enum('placed', 'cooking', 'waiting for courier', 'delivering', 'delivered') not null default 'placed', `payment_type` enum('cash', 'online') not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `orders` add constraint `orders_userid_foreign` foreign key (`userid`) references `users` (`id`);
create table `ordersfoods` (`id` bigint unsigned not null auto_increment primary key, `orderid` bigint unsigned not null, `foodid` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `ordersfoods` add constraint `ordersfoods_orderid_foreign` foreign key (`orderid`) references `orders` (`id`);
alter table `ordersfoods` add constraint `ordersfoods_foodid_foreign` foreign key (`foodid`) references `foods` (`id`);
alter table `orders` add `courierid` bigint unsigned null;
alter table `orders` add constraint `orders_courierid_foreign` foreign key (`courierid`) references `users` (`id`);
create table `categories` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
create table `category_food` (`id` bigint unsigned not null auto_increment primary key, `food_id` bigint unsigned not null, `category_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `users` add `address` varchar(255) null, add `mobile` varchar(255) null;
